name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if no changes'
        required: false
        default: false
        type: boolean

concurrency:
  group: docker-build
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository with submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Update submodule to latest
      - name: Update submodule to latest
        run: |
          git submodule update --remote --merge opencut

          # Check if there are changes
          if [ -n "$(git status --porcelain)" ]; then
            echo "Submodule has updates"
            echo "submodule_updated=true" >> $GITHUB_ENV

            # Configure git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            # Commit and push submodule update
            git add opencut
            git commit -m "Update OpenCut submodule to latest version"
            git push
          else
            echo "Submodule is up to date"
            echo "submodule_updated=false" >> $GITHUB_ENV
          fi

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Generate metadata
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/opencut
          tags: |
            type=raw,value=latest
            type=sha,prefix=main-

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Step 7: Summary
      - name: Build Summary
        if: always()
        run: |
          echo "## ✅ Docker Image Built and Pushed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Details:" >> $GITHUB_STEP_SUMMARY
          echo "- **Docker Image**: ${{ secrets.DOCKERHUB_USERNAME }}/opencut" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit SHA**: $(git rev-parse HEAD)" >> $GITHUB_STEP_SUMMARY
          echo "- **Submodule Updated**: ${{ env.submodule_updated }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Event**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY