name: OpenCut Docker Build and Push (Secure)

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if no new commits'
        required: false
        default: false
        type: boolean

# Limit concurrent runs to prevent abuse
concurrency:
  group: docker-build
  cancel-in-progress: false

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    # Only allow specific users to run this workflow manually
    if: |
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' &&
      (github.actor == 'developer024' ||
       github.actor == 'your-trusted-user' ||
       github.repository_owner == github.actor)

    steps:
      # Step 1: Checkout this repository
      - name: Checkout Docker build repository
        uses: actions/checkout@v4
        with:
          path: docker-repo

      # Step 2: Checkout OpenCut repository
      - name: Checkout OpenCut repository
        uses: actions/checkout@v4
        with:
          repository: OpenCut-app/OpenCut
          ref: main
          path: opencut
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Check for new commits and rate limiting
      - name: Check for new commits
        id: check-commits
        run: |
          cd opencut

          # Get the latest commit SHA
          LATEST_SHA=$(git rev-parse HEAD)
          echo "latest_sha=${LATEST_SHA}" >> $GITHUB_OUTPUT

          # Check if we have a record of the last built commit
          if [ -f "../docker-repo/.last-built-sha" ]; then
            LAST_BUILT_SHA=$(cat ../docker-repo/.last-built-sha)
            echo "Last built SHA: ${LAST_BUILT_SHA}"
            echo "Latest SHA: ${LATEST_SHA}"

            # Check last build time (prevent rapid rebuilds)
            if [ -f "../docker-repo/.last-build-time" ]; then
              LAST_BUILD_TIME=$(cat ../docker-repo/.last-build-time)
              CURRENT_TIME=$(date +%s)
              TIME_DIFF=$((CURRENT_TIME - LAST_BUILD_TIME))

              # If less than 30 minutes (1800 seconds) since last build
              if [ $TIME_DIFF -lt 1800 ] && [ "${{ github.event.inputs.force_build }}" != "true" ]; then
                echo "⚠️ Last build was less than 30 minutes ago. Skipping to prevent abuse."
                echo "should_build=false" >> $GITHUB_OUTPUT
                exit 0
              fi
            fi

            if [ "${LAST_BUILT_SHA}" = "${LATEST_SHA}" ] && [ "${{ github.event.inputs.force_build }}" != "true" ]; then
              echo "No new commits found. Skipping build."
              echo "should_build=false" >> $GITHUB_OUTPUT
            else
              echo "New commits found or force build requested. Proceeding with build."
              echo "should_build=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous build record found. Proceeding with build."
            echo "should_build=true" >> $GITHUB_OUTPUT
          fi

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        if: steps.check-commits.outputs.should_build == 'true'
        uses: docker/setup-buildx-action@v3

      # Step 5: Login to DockerHub
      - name: Login to DockerHub
        if: steps.check-commits.outputs.should_build == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Get metadata for tags
      - name: Generate Docker metadata
        if: steps.check-commits.outputs.should_build == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/opencut
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      # Step 7: Build and push Docker image
      - name: Build and push Docker image
        if: steps.check-commits.outputs.should_build == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./opencut
          file: ./opencut/apps/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Step 8: Update last built SHA and timestamp
      - name: Update build records
        if: steps.check-commits.outputs.should_build == 'true'
        run: |
          echo "${{ steps.check-commits.outputs.latest_sha }}" > docker-repo/.last-built-sha
          date +%s > docker-repo/.last-build-time
          cd docker-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .last-built-sha .last-build-time
          git commit -m "Update last built SHA to ${{ steps.check-commits.outputs.latest_sha }}" || echo "No changes to commit"
          git push || echo "No changes to push"

      # Step 9: Summary
      - name: Build Summary
        if: always()
        run: |
          if [ "${{ steps.check-commits.outputs.should_build }}" = "true" ]; then
            echo "## ✅ Docker Image Built and Pushed" >> $GITHUB_STEP_SUMMARY
            echo "- **Repository**: OpenCut-app/OpenCut" >> $GITHUB_STEP_SUMMARY
            echo "- **Commit SHA**: ${{ steps.check-commits.outputs.latest_sha }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Docker Image**: ${{ secrets.DOCKERHUB_USERNAME }}/opencut" >> $GITHUB_STEP_SUMMARY
            echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Trigger type**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          else
            echo "## ⏭️ Build Skipped" >> $GITHUB_STEP_SUMMARY
            echo "No new commits found in OpenCut-app/OpenCut repository or rate limit applied." >> $GITHUB_STEP_SUMMARY
            echo "- **Latest SHA**: ${{ steps.check-commits.outputs.latest_sha }}" >> $GITHUB_STEP_SUMMARY
            echo "- **Triggered by**: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          fi